[package]
name = "gagalworks_site"
version = "0.1.1"
authors = ["Leonar Tambunan" ]
edition = "2021"
resolver = "2"

[dependencies]
dioxus = { version = "0.6.3", features = ["router", "launch"] }
dioxus-web = { version = "0.6.3", features = ["hydrate"], optional = true }

# gagalworks_docs_router = { workspace = true }

dioxus-material-icons = { version = "3.0.0" }
# syntect-html = { workspace = true }
# mdbook-shared = { workspace = true }
# use-mdbook = { workspace = true }
gagalworks-search = { workspace = true }

askama_escape = { version = "0.10.3", optional = true }
getrandom = { workspace = true, features = ["js"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
log = "0.4.17"
wasm-bindgen = { version = "0.2.99", features = ["enable-interning"] }
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen= "0.6.4"
once_cell = "1.17.1"
tokio = { version = "1.29.0", features = ["full"], optional = true }
axum = { workspace = true, optional = true }
http = { version = "1.0.0", optional = true }
reqwest = { version = "0.12.12", features = ["json", "__tls"] }
gloo-storage = { version = "0.3.0", optional = true }
web-sys = { version = "0.3.77", features = [
    "Document",
    "HtmlDocument",
    "Window",
    "Event",
    "AddEventListenerOptions",
    "Navigator",
] }
slab = "0.4.8"
chrono = { workspace = true, features = ["serde"] }
futures = "0.3.28"
async-recursion = "1.0.4"
futures-util = "0.3"
gloo-timers = { version = "0.3.0", features = ["futures"] }
js-sys = "0.3.64"
automod = "1.0.13"
stork-lib = { workspace = true, features = ["build-v3",], default-features = false }

base64 = "0.22"

[features]
default = []
fullstack = [
    "dioxus/fullstack",
    # "gagalworks_docs_router/fullstack",
]
web = [
    "dioxus/web",
    # "gagalworks_docs_router/web",
]
server = [
    "dioxus/server",
    "dioxus/ssr",
    "dep:askama_escape",
]
production = [
    # "gagalworks_docs_router/production",
]
