[package]
name = "gagalworks-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
toml = "0.8.1"
stork-lib = { workspace = true, features = ["build-v3"], default-features = false }
bytes = { version = "1.3.0", features = ["serde"] }
slab = "0.4.8"
dioxus-router = { version = "0.6.0" }
yazi = { workspace = true }
once_cell = "1.18.0"
gagalworks-search-macro = { workspace = true }
gagalworks-search-shared = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { workspace = true, features = ["js"] }
